$(document).ready(function (){
  $('.box1').mouseenter(function(){
    $('.intro1').fadeIn('normal');
  });
  $('.box1').mouseleave(function(){
    $('.intro1').fadeOut('normal');
  });
  $('.box2').mouseenter(function(){
    $('.intro2').fadeIn('normal');
  });
  $('.box2').mouseleave(function(){
    $('.intro2').fadeOut('normal');
  });
  $('.box3').mouseenter(function(){
    $('.intro3').fadeIn('normal');
  });
  $('.box3').mouseleave(function(){
    $('.intro3').fadeOut('normal');
  });
  $('.box4').mouseenter(function(){
    $('.intro4').fadeIn('normal');
  });
  $('.box4').mouseleave(function(){
    $('.intro4').fadeOut('normal');
  });
  $('.box5').mouseenter(function(){
    $('.intro5').fadeIn('normal');
  });
  $('.box5').mouseleave(function(){
    $('.intro5').fadeOut('normal');
  });
  $('.box6').mouseenter(function(){
    $('.intro6').fadeIn('normal');
  });
  $('.box6').mouseleave(function(){
    $('.intro6').fadeOut('normal');
  });
  $('.box7').mouseenter(function(){
    $('.intro7').fadeIn('normal');
  });
  $('.box7').mouseleave(function(){
    $('.intro7').fadeOut('normal');
  });
});
